/**
 * Dummy data for demo/presentation purposes.
 * Used as fallback when API returns empty results.
 */

import type { Panthulugaru, Photographer, Caterer, Article, Ritual, SubRitual, Festival, TempleJob } from '@/types';

// ─── Featured Pandits ───────────────────────────────────────────────

export const DUMMY_PANDITS: Panthulugaru[] = [
  {
    id: 'demo-p1',
    firstName: 'Venkata',
    lastName: 'Subrahmanyam',
    email: 'venkata@demo.com',
    phone: '+919876543210',
    slug: 'venkata-subrahmanyam',
    profileImage: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=200&h=200&fit=crop&crop=face',
    experience: 25,
    qualification: 'M.A. Sanskrit, Vedic Studies',
    aboutMe: 'With over 25 years of experience in performing Vedic rituals, I specialize in Griha Pravesam, Vivaha, and Satyanarayana Puja. Trained at Tirumala Tirupati Devasthanams.',
    languages: ['Telugu', 'Sanskrit', 'Hindi', 'English'],
    specializations: ['Griha Pravesam', 'Vivaha', 'Satyanarayana Puja', 'Navagraha Homam'],
    rituals: [],
    serviceAreas: [{ state: 'Telangana', district: 'Hyderabad', city: 'Hyderabad' }],
    primaryCity: 'Hyderabad',
    primaryState: 'Telangana',
    rating: 4.9,
    reviewCount: 156,
    totalBookings: 420,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    onboardingStatus: 'COMPLETED',
    onboardingStep: 5,
    minimumPricing: 2500,
    gallery: [],
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'demo-p2',
    firstName: 'Raghunath',
    lastName: 'Sharma',
    email: 'raghunath@demo.com',
    phone: '+919876543211',
    slug: 'raghunath-sharma',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    experience: 18,
    qualification: 'Shastri, Jyotish Visharad',
    aboutMe: 'Experienced in all Hindu ceremonies with special expertise in astrology-based muhurtham selection and Navagraha remedies.',
    languages: ['Telugu', 'Sanskrit', 'Hindi'],
    specializations: ['Navagraha Puja', 'Vastu Shanti', 'Muhurtham', 'Homam'],
    rituals: [],
    serviceAreas: [{ state: 'Telangana', district: 'Rangareddi', city: 'Shamshabad' }],
    primaryCity: 'Shamshabad',
    primaryState: 'Telangana',
    rating: 4.8,
    reviewCount: 98,
    totalBookings: 310,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    onboardingStatus: 'COMPLETED',
    onboardingStep: 5,
    minimumPricing: 3000,
    gallery: [],
    createdAt: '2023-03-10T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: 'demo-p3',
    firstName: 'Srinivasa',
    lastName: 'Acharya',
    email: 'srinivasa@demo.com',
    phone: '+919876543212',
    slug: 'srinivasa-acharya',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    experience: 30,
    qualification: 'Vidwan, Agama Shastra',
    aboutMe: 'Senior Vedic scholar with 30 years of temple and household puja experience. Specialist in Agama-based temple rituals and Kumbhabhishekam.',
    languages: ['Tamil', 'Sanskrit', 'Telugu', 'English'],
    specializations: ['Temple Rituals', 'Kumbhabhishekam', 'Ganapathi Homam', 'Rudra Abhishekam'],
    rituals: [],
    serviceAreas: [{ state: 'Tamil Nadu', district: 'Chennai', city: 'Chennai' }],
    primaryCity: 'Chennai',
    primaryState: 'Tamil Nadu',
    rating: 4.9,
    reviewCount: 203,
    totalBookings: 680,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    onboardingStatus: 'COMPLETED',
    onboardingStep: 5,
    minimumPricing: 3500,
    gallery: [],
    createdAt: '2022-06-01T00:00:00Z',
    updatedAt: '2024-12-05T00:00:00Z',
  },
  {
    id: 'demo-p4',
    firstName: 'Krishna',
    lastName: 'Bhatt',
    email: 'krishna@demo.com',
    phone: '+919876543213',
    slug: 'krishna-bhatt',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    experience: 15,
    qualification: 'B.A. Sanskrit, Purohit Training',
    aboutMe: 'Young and dynamic pandit combining traditional Vedic knowledge with modern approach. Expert in naming ceremonies and wedding rituals.',
    languages: ['Kannada', 'Sanskrit', 'Hindi', 'English'],
    specializations: ['Naming Ceremony', 'Wedding Rituals', 'Annaprasana', 'Upanayanam'],
    rituals: [],
    serviceAreas: [{ state: 'Karnataka', district: 'Bengaluru', city: 'Bengaluru' }],
    primaryCity: 'Bengaluru',
    primaryState: 'Karnataka',
    rating: 4.7,
    reviewCount: 72,
    totalBookings: 185,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    onboardingStatus: 'COMPLETED',
    onboardingStep: 5,
    minimumPricing: 2000,
    gallery: [],
    createdAt: '2023-09-20T00:00:00Z',
    updatedAt: '2024-11-28T00:00:00Z',
  },
  {
    id: 'demo-p5',
    firstName: 'Narasimha',
    lastName: 'Murthy',
    email: 'narasimha@demo.com',
    phone: '+919876543214',
    slug: 'narasimha-murthy',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
    experience: 22,
    qualification: 'M.A. Vedanta, Jyotish Acharya',
    aboutMe: 'Jyotish Acharya with deep knowledge in Vedic astrology and horoscope matching. Also performs all types of homams and pujas.',
    languages: ['Telugu', 'Hindi', 'Sanskrit'],
    specializations: ['Horoscope Matching', 'Jyotish Consultation', 'Lakshmi Puja', 'Shanti Puja'],
    rituals: [],
    serviceAreas: [{ state: 'Andhra Pradesh', district: 'Visakhapatnam', city: 'Visakhapatnam' }],
    primaryCity: 'Visakhapatnam',
    primaryState: 'Andhra Pradesh',
    rating: 4.8,
    reviewCount: 134,
    totalBookings: 390,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    onboardingStatus: 'COMPLETED',
    onboardingStep: 5,
    minimumPricing: 2800,
    gallery: [],
    createdAt: '2022-11-10T00:00:00Z',
    updatedAt: '2024-12-02T00:00:00Z',
  },
  {
    id: 'demo-p6',
    firstName: 'Ramesh',
    lastName: 'Dikshitar',
    email: 'ramesh@demo.com',
    phone: '+919876543215',
    slug: 'ramesh-dikshitar',
    profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face',
    experience: 20,
    qualification: 'Agama Shastra, Pancha Tantra',
    aboutMe: 'Expert in Agama-based temple rituals and complex homams. Performed rituals across major temples in South India.',
    languages: ['Tamil', 'Sanskrit', 'English'],
    specializations: ['Sudarshana Homam', 'Maha Mrityunjaya', 'Chandi Homam', 'Vastu Puja'],
    rituals: [],
    serviceAreas: [{ state: 'Tamil Nadu', district: 'Coimbatore', city: 'Coimbatore' }],
    primaryCity: 'Coimbatore',
    primaryState: 'Tamil Nadu',
    rating: 4.6,
    reviewCount: 89,
    totalBookings: 275,
    isVerified: true,
    isAvailable: false,
    status: 'ACTIVE',
    onboardingStatus: 'COMPLETED',
    onboardingStep: 5,
    minimumPricing: 3200,
    gallery: [],
    createdAt: '2023-02-14T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
];

// ─── Photographers ──────────────────────────────────────────────────

export const DUMMY_PHOTOGRAPHERS: Photographer[] = [
  {
    id: 'demo-ph1',
    firstName: 'Arun',
    lastName: 'Patel',
    slug: 'arun-patel',
    email: 'arun@demo.com',
    phone: '+919876543220',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face',
    aboutMe: 'Award-winning photographer specializing in Hindu ceremonies, weddings, and spiritual events. 12+ years capturing sacred moments.',
    experience: 12,
    specializations: ['Wedding Photography', 'Puja Documentation', 'Temple Photography', 'Portrait'],
    languages: ['Telugu', 'Hindi', 'English'],
    serviceAreas: [{ state: 'Telangana', district: 'Hyderabad', city: 'Hyderabad' }],
    primaryCity: 'Hyderabad',
    primaryState: 'Telangana',
    portfolio: [],
    videography: true,
    dronePhotography: true,
    equipment: ['Canon EOS R5', 'DJI Mavic 3', 'Sony FX6'],
    pricePerDay: 25000,
    pricePerEvent: 15000,
    rating: 4.8,
    reviewCount: 67,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    createdAt: '2023-05-01T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'demo-ph2',
    firstName: 'Meera',
    lastName: 'Krishnan',
    slug: 'meera-krishnan',
    email: 'meera@demo.com',
    phone: '+919876543221',
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    aboutMe: 'Passionate about capturing the beauty of traditional Indian ceremonies. Specialized in candid and artistic event photography.',
    experience: 8,
    specializations: ['Candid Photography', 'Event Photography', 'Bridal Portraits', 'Ceremony Documentation'],
    languages: ['Tamil', 'English', 'Hindi'],
    serviceAreas: [{ state: 'Tamil Nadu', district: 'Chennai', city: 'Chennai' }],
    primaryCity: 'Chennai',
    primaryState: 'Tamil Nadu',
    portfolio: [],
    videography: true,
    dronePhotography: false,
    pricePerDay: 20000,
    pricePerEvent: 12000,
    rating: 4.7,
    reviewCount: 45,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    createdAt: '2023-07-15T00:00:00Z',
    updatedAt: '2024-11-20T00:00:00Z',
  },
  {
    id: 'demo-ph3',
    firstName: 'Vikram',
    lastName: 'Reddy',
    slug: 'vikram-reddy',
    email: 'vikram@demo.com',
    phone: '+919876543222',
    profileImage: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=200&h=200&fit=crop&crop=face',
    aboutMe: 'Professional photographer with expertise in temple architecture photography and spiritual event documentation.',
    experience: 15,
    specializations: ['Temple Photography', 'Cultural Events', 'Drone Shots', 'Cinematic Videos'],
    languages: ['Telugu', 'Hindi', 'English'],
    serviceAreas: [{ state: 'Andhra Pradesh', district: 'Vijayawada', city: 'Vijayawada' }],
    primaryCity: 'Vijayawada',
    primaryState: 'Andhra Pradesh',
    portfolio: [],
    videography: true,
    dronePhotography: true,
    pricePerDay: 30000,
    pricePerEvent: 18000,
    rating: 4.9,
    reviewCount: 82,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    createdAt: '2022-09-01T00:00:00Z',
    updatedAt: '2024-12-03T00:00:00Z',
  },
];

// ─── Caterers ───────────────────────────────────────────────────────

export const DUMMY_CATERERS: Caterer[] = [
  {
    id: 'demo-c1',
    businessName: 'Sri Lakshmi Catering',
    ownerName: 'Lakshmi Devi',
    slug: 'sri-lakshmi-catering',
    email: 'lakshmi@demo.com',
    phone: '+919876543230',
    profileImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=200&h=200&fit=crop',
    aboutUs: 'Traditional South Indian vegetarian catering for all Hindu ceremonies. Pure sattvic food prepared with devotion.',
    experience: 20,
    cuisineTypes: ['South Indian', 'North Indian', 'Traditional Telugu'],
    menuTypes: ['Vegetarian', 'Sattvic', 'Festival Special'],
    serviceAreas: [{ state: 'Telangana', district: 'Hyderabad', city: 'Hyderabad' }],
    primaryCity: 'Hyderabad',
    primaryState: 'Telangana',
    minPlateCount: 50,
    maxPlateCount: 2000,
    pricePerPlate: 350,
    vegetarianOnly: true,
    gallery: [],
    rating: 4.7,
    reviewCount: 123,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    createdAt: '2022-04-01T00:00:00Z',
    updatedAt: '2024-12-01T00:00:00Z',
  },
  {
    id: 'demo-c2',
    businessName: 'Annapurna Bhojanalay',
    ownerName: 'Ramesh Gupta',
    slug: 'annapurna-bhojanalay',
    email: 'annapurna@demo.com',
    phone: '+919876543231',
    profileImage: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=200&h=200&fit=crop',
    aboutUs: 'Multi-cuisine catering with 15+ years serving wedding ceremonies, pujas, and spiritual gatherings across South India.',
    experience: 15,
    cuisineTypes: ['South Indian', 'North Indian', 'Andhra', 'Rajasthani'],
    menuTypes: ['Vegetarian', 'Non-Vegetarian', 'Jain'],
    serviceAreas: [{ state: 'Karnataka', district: 'Bengaluru', city: 'Bengaluru' }],
    primaryCity: 'Bengaluru',
    primaryState: 'Karnataka',
    minPlateCount: 100,
    maxPlateCount: 5000,
    pricePerPlate: 450,
    vegetarianOnly: false,
    gallery: [],
    rating: 4.6,
    reviewCount: 89,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    createdAt: '2023-01-10T00:00:00Z',
    updatedAt: '2024-11-25T00:00:00Z',
  },
  {
    id: 'demo-c3',
    businessName: 'Bhagya Lakshmi Foods',
    ownerName: 'Suresh Kumar',
    slug: 'bhagya-lakshmi-foods',
    email: 'bhagya@demo.com',
    phone: '+919876543232',
    profileImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=200&h=200&fit=crop',
    aboutUs: 'Specialized in traditional Telugu wedding catering. Known for authentic Brahmin-style cooking for ceremonies.',
    experience: 25,
    cuisineTypes: ['Traditional Telugu', 'Brahmin Style', 'Festival Specials'],
    menuTypes: ['Pure Vegetarian', 'Sattvic', 'Prasadam'],
    serviceAreas: [{ state: 'Telangana', district: 'Hyderabad', city: 'Secunderabad' }],
    primaryCity: 'Secunderabad',
    primaryState: 'Telangana',
    minPlateCount: 25,
    maxPlateCount: 1000,
    pricePerPlate: 300,
    vegetarianOnly: true,
    gallery: [],
    rating: 4.8,
    reviewCount: 156,
    isVerified: true,
    isAvailable: true,
    status: 'ACTIVE',
    createdAt: '2021-08-01T00:00:00Z',
    updatedAt: '2024-12-04T00:00:00Z',
  },
];

// ─── Articles ───────────────────────────────────────────────────────

export const DUMMY_ARTICLES: Article[] = [
  {
    id: 'demo-a1',
    title: 'The Complete Guide to Griha Pravesam: Traditions, Rituals & Significance',
    slug: 'complete-guide-griha-pravesam',
    excerpt: 'Griha Pravesam, the Hindu housewarming ceremony, is one of the most important rituals performed when entering a new home. Learn about its deep spiritual significance.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop',
    author: 'Pandit Venkatesh',
    category: 'Rituals',
    tags: ['Griha Pravesam', 'Housewarming', 'Vastu'],
    status: 'PUBLISHED',
    viewCount: 3450,
    publishedAt: '2024-11-15T00:00:00Z',
    createdAt: '2024-11-15T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
  {
    id: 'demo-a2',
    title: 'Understanding Navagraha Puja: How Planetary Worship Can Transform Your Life',
    slug: 'understanding-navagraha-puja',
    excerpt: 'Navagraha Puja is performed to appease the nine celestial bodies that influence our lives. Discover which graha affects you and the remedies available.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1532968961962-8a0cb3a2d4f5?w=600&h=400&fit=crop',
    author: 'Dr. Suresh Joshi',
    category: 'Astrology',
    tags: ['Navagraha', 'Planets', 'Remedies'],
    status: 'PUBLISHED',
    viewCount: 2890,
    publishedAt: '2024-11-10T00:00:00Z',
    createdAt: '2024-11-10T00:00:00Z',
    updatedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'demo-a3',
    title: 'Satyanarayana Puja: Step-by-Step Guide for Performing at Home',
    slug: 'satyanarayana-puja-guide',
    excerpt: 'Learn the complete procedure for Satyanarayana Puja, one of the most commonly performed Hindu pujas. Includes mantras, samagri list, and procedure.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1604608672516-f1b9b1d37076?w=600&h=400&fit=crop',
    author: 'Pandit Ramakrishna',
    category: 'Rituals',
    tags: ['Satyanarayana', 'Puja', 'Home Rituals'],
    status: 'PUBLISHED',
    viewCount: 5120,
    publishedAt: '2024-10-25T00:00:00Z',
    createdAt: '2024-10-25T00:00:00Z',
    updatedAt: '2024-10-25T00:00:00Z',
  },
  {
    id: 'demo-a4',
    title: 'The Importance of Muhurtham: Choosing the Right Time for Ceremonies',
    slug: 'importance-of-muhurtham',
    excerpt: 'In Hindu tradition, selecting an auspicious muhurtham is crucial for the success of any ceremony. Understanding Panchangam and timing selection.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=600&h=400&fit=crop',
    author: 'Jyotish Narasimha',
    category: 'Astrology',
    tags: ['Muhurtham', 'Panchangam', 'Timing'],
    status: 'PUBLISHED',
    viewCount: 1860,
    publishedAt: '2024-10-18T00:00:00Z',
    createdAt: '2024-10-18T00:00:00Z',
    updatedAt: '2024-10-18T00:00:00Z',
  },
  {
    id: 'demo-a5',
    title: 'Upanayanam Ceremony: Sacred Thread Ceremony Explained',
    slug: 'upanayanam-ceremony-explained',
    excerpt: 'Upanayanam marks the beginning of formal Vedic education. Learn about its significance, rituals involved, and how to prepare for this sacred ceremony.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1606567595334-d39972c85dbe?w=600&h=400&fit=crop',
    author: 'Acharya Srinivasan',
    category: 'Traditions',
    tags: ['Upanayanam', 'Sacred Thread', 'Vedic Education'],
    status: 'PUBLISHED',
    viewCount: 2340,
    publishedAt: '2024-10-05T00:00:00Z',
    createdAt: '2024-10-05T00:00:00Z',
    updatedAt: '2024-10-05T00:00:00Z',
  },
  {
    id: 'demo-a6',
    title: 'Hindu Wedding Rituals: A Complete Guide to Vivaha Ceremonies',
    slug: 'hindu-wedding-rituals-guide',
    excerpt: 'From Kanyadaanam to Saptapadi, explore the beautiful and meaningful rituals that make up a traditional Hindu wedding ceremony.',
    content: '',
    coverImage: 'https://images.unsplash.com/photo-1583089892943-e02e5b017b6a?w=600&h=400&fit=crop',
    author: 'Pandit Venkatesh',
    category: 'Traditions',
    tags: ['Wedding', 'Vivaha', 'Marriage'],
    status: 'PUBLISHED',
    viewCount: 4560,
    publishedAt: '2024-09-20T00:00:00Z',
    createdAt: '2024-09-20T00:00:00Z',
    updatedAt: '2024-09-20T00:00:00Z',
  },
];

// ─── Rituals ────────────────────────────────────────────────────────

export const DUMMY_RITUALS: Ritual[] = [
  {
    id: 'demo-r1',
    name: 'Griha Pravesam',
    description: 'The sacred housewarming ceremony performed when entering a new home. Includes Ganapathi Puja, Vastu Puja, Navagraha Puja, and Griha Shanti.',
    category: 'Home Ceremonies',
    isActive: true,
    subRituals: [
      { id: 'sr1', name: 'Ganapathi Puja', ritualId: 'demo-r1', isActive: true },
      { id: 'sr2', name: 'Vastu Shanti', ritualId: 'demo-r1', isActive: true },
      { id: 'sr3', name: 'Navagraha Homam', ritualId: 'demo-r1', isActive: true },
      { id: 'sr4', name: 'Milk Boiling Ceremony', ritualId: 'demo-r1', isActive: true },
    ],
  },
  {
    id: 'demo-r2',
    name: 'Satyanarayana Puja',
    description: 'One of the most widely performed Hindu pujas dedicated to Lord Vishnu. Commonly performed for prosperity, well-being, and fulfillment of wishes.',
    category: 'Regular Pujas',
    isActive: true,
    subRituals: [
      { id: 'sr5', name: 'Puja Vidhanam', ritualId: 'demo-r2', isActive: true },
      { id: 'sr6', name: 'Katha Parayanam', ritualId: 'demo-r2', isActive: true },
      { id: 'sr7', name: 'Prasad Distribution', ritualId: 'demo-r2', isActive: true },
    ],
  },
  {
    id: 'demo-r3',
    name: 'Vivaha (Wedding)',
    description: 'The sacred Hindu marriage ceremony encompassing multiple rituals spanning 2-3 days including Pellikuthuru, Muhurtham, and Appagintalu.',
    category: 'Life Events',
    isActive: true,
    subRituals: [
      { id: 'sr8', name: 'Pellikuthuru', ritualId: 'demo-r3', isActive: true },
      { id: 'sr9', name: 'Kanyadaanam', ritualId: 'demo-r3', isActive: true },
      { id: 'sr10', name: 'Saptapadi', ritualId: 'demo-r3', isActive: true },
      { id: 'sr11', name: 'Talambralu', ritualId: 'demo-r3', isActive: true },
    ],
  },
  {
    id: 'demo-r4',
    name: 'Naming Ceremony (Namakaranam)',
    description: 'The naming ceremony for a newborn child, performed on an auspicious day after birth. Includes Ganapathi Puja and star-based name selection.',
    category: 'Life Events',
    isActive: true,
    subRituals: [
      { id: 'sr12', name: 'Ganapathi Puja', ritualId: 'demo-r4', isActive: true },
      { id: 'sr13', name: 'Name Announcement', ritualId: 'demo-r4', isActive: true },
    ],
  },
  {
    id: 'demo-r5',
    name: 'Annaprasana (First Rice)',
    description: 'The ceremony of feeding solid food to a baby for the first time. Usually performed during the 6th or 7th month after birth.',
    category: 'Life Events',
    isActive: true,
    subRituals: [],
  },
  {
    id: 'demo-r6',
    name: 'Navagraha Puja',
    description: 'Puja to appease the nine planetary deities for protection from malefic effects and to gain beneficial planetary influences.',
    category: 'Remedial Pujas',
    isActive: true,
    subRituals: [
      { id: 'sr14', name: 'Navagraha Homam', ritualId: 'demo-r6', isActive: true },
      { id: 'sr15', name: 'Graha Shanti', ritualId: 'demo-r6', isActive: true },
    ],
  },
  {
    id: 'demo-r7',
    name: 'Ganapathi Homam',
    description: 'Sacred fire ritual dedicated to Lord Ganesha, the remover of obstacles. Performed before any new venture or important undertaking.',
    category: 'Homams',
    isActive: true,
    subRituals: [],
  },
  {
    id: 'demo-r8',
    name: 'Vastu Puja',
    description: 'Performed to remove Vastu doshas and bring harmony, prosperity, and positive energy to a home or commercial space.',
    category: 'Home Ceremonies',
    isActive: true,
    subRituals: [],
  },
  {
    id: 'demo-r9',
    name: 'Upanayanam (Thread Ceremony)',
    description: 'The sacred thread ceremony marking the beginning of formal Vedic education. One of the most important samskaras in Hindu tradition.',
    category: 'Life Events',
    isActive: true,
    subRituals: [
      { id: 'sr16', name: 'Sankalpa', ritualId: 'demo-r9', isActive: true },
      { id: 'sr17', name: 'Yagnopavita Dharana', ritualId: 'demo-r9', isActive: true },
      { id: 'sr18', name: 'Gayatri Upadesha', ritualId: 'demo-r9', isActive: true },
    ],
  },
];

// ─── Testimonials ───────────────────────────────────────────────────

export const DUMMY_TESTIMONIALS = [
  {
    id: 't1',
    name: 'Priya Reddy',
    location: 'Hyderabad',
    avatar: 'PR',
    rating: 5,
    text: 'We found the most knowledgeable pandit for our Griha Pravesam through Panthulu Garu. The entire process was seamless, from booking to the actual ceremony. Highly recommended!',
    ritual: 'Griha Pravesam',
  },
  {
    id: 't2',
    name: 'Suresh & Lavanya',
    location: 'Chennai',
    avatar: 'SL',
    rating: 5,
    text: 'Our wedding was made perfect by the pandit we found here. He explained every ritual beautifully and made our families feel at ease. The platform is a blessing!',
    ritual: 'Wedding Ceremony',
  },
  {
    id: 't3',
    name: 'Ramakrishna Murthy',
    location: 'Bengaluru',
    avatar: 'RM',
    rating: 5,
    text: 'Used Panthulu Garu for our son\'s Upanayanam. The pandit was punctual, well-versed in rituals, and very patient with explaining the significance to our son.',
    ritual: 'Upanayanam',
  },
  {
    id: 't4',
    name: 'Anita Sharma',
    location: 'Vijayawada',
    avatar: 'AS',
    rating: 4,
    text: 'Excellent service! Found a pandit for Satyanarayana Puja within hours. The platform makes it so easy to compare pandits and read reviews before booking.',
    ritual: 'Satyanarayana Puja',
  },
  {
    id: 't5',
    name: 'Gopala Krishna',
    location: 'Hyderabad',
    avatar: 'GK',
    rating: 5,
    text: 'The horoscope matching service was incredibly accurate. The pandit provided detailed analysis and muhurtham suggestions for our daughter\'s wedding. Very satisfied!',
    ritual: 'Horoscope Matching',
  },
  {
    id: 't6',
    name: 'Padma Lakshmi',
    location: 'Warangal',
    avatar: 'PL',
    rating: 5,
    text: 'We have been using Panthulu Garu for all family ceremonies for the past 2 years. Consistently great service and the pandits are always knowledgeable and respectful.',
    ritual: 'Multiple Ceremonies',
  },
  {
    id: 't7',
    name: 'Venkatesh Iyer',
    location: 'Mumbai',
    avatar: 'VI',
    rating: 5,
    text: 'Booked a pandit for Ganesh Chaturthi celebrations at our society. The pandit was wonderful with over 200 families participating. Truly a divine experience!',
    ritual: 'Ganesh Chaturthi',
  },
  {
    id: 't8',
    name: 'Meena Kumari',
    location: 'Tirupati',
    avatar: 'MK',
    rating: 5,
    text: 'The Vastu Puja for our new office was conducted so professionally. The pandit explained every step and gave us practical Vastu tips. Business has been great since!',
    ritual: 'Vastu Puja',
  },
  {
    id: 't9',
    name: 'Ravi Teja Reddy',
    location: 'Vizag',
    avatar: 'RT',
    rating: 4,
    text: 'Found an excellent pandit for my daughter\'s Annaprasana ceremony. He was patient, traditional, and made the ceremony very special for our family.',
    ritual: 'Annaprasana',
  },
  {
    id: 't10',
    name: 'Sridevi Naidu',
    location: 'Guntur',
    avatar: 'SN',
    rating: 5,
    text: 'Amazing platform! The pandit conducted Navagraha Homam with perfect Vedic mantras. My entire family felt the positive energy. Will definitely use again.',
    ritual: 'Navagraha Homam',
  },
];

// ─── Stats ──────────────────────────────────────────────────────────

export const PLATFORM_STATS = {
  totalPandits: 500,
  totalCeremonies: 15000,
  totalCities: 120,
  customerRating: 4.8,
  totalReviews: 8500,
  totalPhotographers: 85,
  totalCaterers: 120,
};

// ─── How It Works Steps ─────────────────────────────────────────────

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: 'Search & Browse',
    description: 'Search for pandits by ritual, location, or name. Browse verified profiles with ratings and reviews.',
    icon: 'Search',
  },
  {
    step: 2,
    title: 'Compare & Choose',
    description: 'Compare pandit profiles, experience, specializations, and pricing. Read genuine reviews from other devotees.',
    icon: 'Users',
  },
  {
    step: 3,
    title: 'Book & Connect',
    description: 'Book your preferred pandit for your ceremony. Get connected directly to discuss ceremony details.',
    icon: 'Calendar',
  },
  {
    step: 4,
    title: 'Ceremony & Review',
    description: 'Enjoy a perfectly conducted ceremony. Share your experience to help other devotees find the right pandit.',
    icon: 'Star',
  },
];

// ─── Upcoming Festivals ─────────────────────────────────────────────

export const DUMMY_FESTIVALS: Festival[] = [
  {
    id: 'f1',
    name: 'Akshaya Tritiya',
    date: '2026-05-15',
    description: 'One of the most auspicious days in the Hindu calendar. Ideal for new beginnings, buying gold, and performing pujas.',
    category: 'Major Festival',
    isNationalHoliday: false,
  },
  {
    id: 'f2',
    name: 'Guru Purnima',
    date: '2026-07-11',
    description: 'A day dedicated to honoring spiritual and academic gurus. Special pujas are performed to show gratitude.',
    category: 'Major Festival',
    isNationalHoliday: false,
  },
  {
    id: 'f3',
    name: 'Ganesh Chaturthi',
    date: '2026-08-22',
    description: 'The grand festival celebrating the birth of Lord Ganesha. Involves installation and worship of Ganesha idols.',
    category: 'Major Festival',
    isNationalHoliday: true,
  },
  {
    id: 'f4',
    name: 'Navaratri',
    date: '2026-10-02',
    description: 'Nine nights of worship dedicated to Goddess Durga. Includes Dussehra/Vijayadashami.',
    category: 'Major Festival',
    isNationalHoliday: true,
  },
  {
    id: 'f5',
    name: 'Diwali',
    date: '2026-10-20',
    description: 'The festival of lights celebrating the victory of good over evil. Lakshmi Puja is the highlight.',
    category: 'Major Festival',
    isNationalHoliday: true,
  },
];

// ─── Temple Jobs ────────────────────────────────────────────────────

export const DUMMY_TEMPLE_JOBS: TempleJob[] = [
  {
    id: 'tj1',
    templeName: 'Sri Venkateswara Temple',
    templeLocation: 'Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    jobTitle: 'Head Priest (Archakar)',
    jobType: 'Full-time',
    description: 'Looking for an experienced archakar to lead daily temple rituals and special ceremonies. Must have knowledge of Agama Shastra.',
    requirements: ['Agama Shastra knowledge', '10+ years experience', 'Telugu & Sanskrit fluency'],
    qualifications: ['Degree in Sanskrit/Vedic Studies', 'Agama certification'],
    salary: '₹40,000 - ₹60,000',
    isActive: true,
    applicationsCount: 12,
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'tj2',
    templeName: 'Sri Rama Temple',
    templeLocation: 'Ameerpet',
    city: 'Hyderabad',
    state: 'Telangana',
    jobTitle: 'Assistant Priest',
    jobType: 'Full-time',
    description: 'Assistant priest position for daily abhishekam, archana, and assisting in special ceremonies. Training will be provided.',
    requirements: ['Basic Sanskrit knowledge', '2+ years experience', 'Willingness to learn'],
    qualifications: ['Sanskrit education preferred'],
    salary: '₹20,000 - ₹30,000',
    isActive: true,
    applicationsCount: 8,
    createdAt: '2024-11-10T00:00:00Z',
    updatedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'tj3',
    templeName: 'Ganesh Temple Trust',
    templeLocation: 'Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    jobTitle: 'Temple Administrator',
    jobType: 'Full-time',
    description: 'Managing daily temple operations, devotee coordination, event planning, and administrative duties.',
    requirements: ['Management experience', 'Good communication', 'Computer literacy'],
    qualifications: ['Graduate degree', 'Admin experience'],
    salary: '₹35,000 - ₹50,000',
    isActive: true,
    applicationsCount: 22,
    createdAt: '2024-10-20T00:00:00Z',
    updatedAt: '2024-10-20T00:00:00Z',
  },
  {
    id: 'tj4',
    templeName: 'Shiva Temple',
    templeLocation: 'Kukatpally',
    city: 'Hyderabad',
    state: 'Telangana',
    jobTitle: 'Vedic Chanting Teacher',
    jobType: 'Part-time',
    description: 'Teach Vedic chanting and mantras to students and devotees. Weekend batches and special sessions during festivals.',
    requirements: ['Expert in Vedic chanting', 'Teaching experience', 'Patient and dedicated'],
    qualifications: ['Ghanapaathi/Kramam expertise'],
    salary: '₹15,000 - ₹25,000',
    isActive: true,
    applicationsCount: 5,
    createdAt: '2024-11-15T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
];

// ─── Special Offers ─────────────────────────────────────────────────

export const DUMMY_OFFERS = [
  {
    id: 'o1',
    title: 'First Booking Offer',
    description: 'Get 15% off on your first pandit booking',
    code: 'FIRST15',
    discount: '15%',
    validTill: '2026-06-30',
    color: 'from-[#FF6B00] to-[#D4AF37]',
  },
  {
    id: 'o2',
    title: 'Festival Season Special',
    description: 'Flat ₹500 off on all festival puja bookings',
    code: 'FESTIVAL500',
    discount: '₹500',
    validTill: '2026-05-31',
    color: 'from-[#361E1E] to-[#CC3333]',
  },
  {
    id: 'o3',
    title: 'Refer & Earn',
    description: 'Refer a friend and both get ₹200 off on next booking',
    code: 'REFER200',
    discount: '₹200',
    validTill: '2026-12-31',
    color: 'from-[#2563EB] to-[#7C3AED]',
  },
];

// ─── Zodiac Signs for Horoscope ─────────────────────────────────────

export const ZODIAC_SIGNS = [
  { name: 'Mesha', english: 'Aries', symbol: '♈', element: 'Fire', dates: 'Mar 21 - Apr 19' },
  { name: 'Vrishabha', english: 'Taurus', symbol: '♉', element: 'Earth', dates: 'Apr 20 - May 20' },
  { name: 'Mithuna', english: 'Gemini', symbol: '♊', element: 'Air', dates: 'May 21 - Jun 20' },
  { name: 'Karka', english: 'Cancer', symbol: '♋', element: 'Water', dates: 'Jun 21 - Jul 22' },
  { name: 'Simha', english: 'Leo', symbol: '♌', element: 'Fire', dates: 'Jul 23 - Aug 22' },
  { name: 'Kanya', english: 'Virgo', symbol: '♍', element: 'Earth', dates: 'Aug 23 - Sep 22' },
  { name: 'Tula', english: 'Libra', symbol: '♎', element: 'Air', dates: 'Sep 23 - Oct 22' },
  { name: 'Vrischika', english: 'Scorpio', symbol: '♏', element: 'Water', dates: 'Oct 23 - Nov 21' },
  { name: 'Dhanu', english: 'Sagittarius', symbol: '♐', element: 'Fire', dates: 'Nov 22 - Dec 21' },
  { name: 'Makara', english: 'Capricorn', symbol: '♑', element: 'Earth', dates: 'Dec 22 - Jan 19' },
  { name: 'Kumbha', english: 'Aquarius', symbol: '♒', element: 'Air', dates: 'Jan 20 - Feb 18' },
  { name: 'Meena', english: 'Pisces', symbol: '♓', element: 'Water', dates: 'Feb 19 - Mar 20' },
];

// ─── FAQ Data ───────────────────────────────────────────────────────

export const FAQ_DATA = [
  {
    question: 'How do I find the right pandit for my ceremony?',
    answer: 'Browse our verified pandit profiles filtered by ritual type, location, and language. Each profile includes ratings, reviews, experience details, and specializations to help you make an informed choice.',
  },
  {
    question: 'Are all pandits on the platform verified?',
    answer: 'Yes, all pandits go through a thorough verification process including identity verification, qualification checks, and reference validation. Look for the "Verified" badge on pandit profiles.',
  },
  {
    question: 'What payment methods do you accept?',
    answer: 'We accept UPI, credit/debit cards, net banking, and popular digital wallets. All payments are processed through secure payment gateways with 100% transaction protection.',
  },
  {
    question: 'Can I cancel or reschedule a booking?',
    answer: 'Yes, you can cancel or reschedule up to 24 hours before the scheduled ceremony. Cancellation before 48 hours receives a full refund. Between 24-48 hours, a small fee applies.',
  },
  {
    question: 'Do pandits provide the puja samagri (items)?',
    answer: 'This varies by pandit. Some pandits provide all necessary puja items, while others may require you to arrange them. Check the pandit\'s profile or discuss during booking for specific requirements.',
  },
  {
    question: 'Can I book a pandit for ceremonies outside my city?',
    answer: 'Yes! Many pandits travel to different cities for ceremonies. Filter by "willing to travel" or check the pandit\'s service areas. Additional travel charges may apply.',
  },
];

// ─── Popular Poojas ─────────────────────────────────────────────────

export const DUMMY_POOJAS = [
  {
    id: 'pj1',
    name: 'Satyanarayana Puja',
    image: '/pooja-images/satyanarayana-puja.svg',
    price: 3500,
    duration: '3-4 hours',
    description: 'Performed for prosperity, success, and fulfillment of wishes. Ideal for housewarmings, festivals, and special occasions.',
    category: 'Prosperity',
    rating: 4.9,
    bookings: 1240,
  },
  {
    id: 'pj2',
    name: 'Ganapathi Homam',
    image: '/pooja-images/ganapathi-homam.svg',
    price: 4500,
    duration: '2-3 hours',
    description: 'Invoking Lord Ganesha to remove obstacles and bring success. Performed before starting new ventures or auspicious events.',
    category: 'Obstacle Removal',
    rating: 4.8,
    bookings: 980,
  },
  {
    id: 'pj3',
    name: 'Navagraha Puja',
    image: '/pooja-images/navagraha-puja.svg',
    price: 5500,
    duration: '4-5 hours',
    description: 'Worship of the nine celestial planets to mitigate doshas and bring planetary harmony into your life.',
    category: 'Astrology',
    rating: 4.7,
    bookings: 756,
  },
  {
    id: 'pj4',
    name: 'Lakshmi Puja',
    image: '/pooja-images/lakshmi-puja.svg',
    price: 3000,
    duration: '2-3 hours',
    description: 'Dedicated to Goddess Lakshmi for wealth, fortune, and prosperity. Especially popular during Diwali and Fridays.',
    category: 'Wealth',
    rating: 4.9,
    bookings: 1580,
  },
  {
    id: 'pj5',
    name: 'Vastu Shanti Puja',
    image: '/pooja-images/vastu-shanti.svg',
    price: 6000,
    duration: '3-4 hours',
    description: 'Performed to neutralize Vastu doshas in homes and offices. Brings positive energy and harmony to the space.',
    category: 'Home & Office',
    rating: 4.8,
    bookings: 620,
  },
  {
    id: 'pj6',
    name: 'Rudrabhishekam',
    image: '/pooja-images/rudrabhishekam.svg',
    price: 5000,
    duration: '3-4 hours',
    description: 'Sacred abhishekam to Lord Shiva with milk, honey, and holy water. For health, peace, and spiritual growth.',
    category: 'Spiritual',
    rating: 4.9,
    bookings: 890,
  },
];
